### ISSUE TITLE
Unstable wifi driver

### ISSUE THREAD

**Issue by jerbob92** [Halolo/orange-pi-zero-distro#10]
Hi,

I noticed the used wifi driver is very unstable. When downloading a large file, wifi would disconnect a lot and give errors with:
RTL871X: ERROR sd_recv_rxfifo: alloc recvbuf FAIL!

I created a new fork: https://github.com/jerbob92/rtl8189fs_linux
It has an older version of the driver, but with some patches cherry-picked to keep compiling working. The version is the same one that's being used by Armbian.
So far, it's looking good on my system.

**Comment by Halolo** [comment]
Hi,

Unfortunatly I don't have the orange pi pc plus board so I can't test it but if you have identified the patches armbian added to this module to make it more stable then it could be added to the recipe.

**Comment by jerbob92** [comment]
I managed to find a new version somewhere hidden in a RockChip kernel. I removed some specific RockChip stuff from the driver and applied fixes to it would compile on a newer kernel.

The changes got merged back: https://github.com/jwrdegoede/rtl8189ES_linux/tree/rtl8189fs
So you just have to change the commit of the driver to cddb07311ec03157643c44154498c9f2268fc431

**Comment by Halolo** [comment]
even better. It's updated.

Thank you.
