### ISSUE TITLE
enable uart1

### ISSUE THREAD

**Issue by serra82** [Halolo/orange-pi-zero-distro#11]
how can I enable uart1 (dev/ttyS1) with openmbedded?

In armbian is sufficient add "overlays=uart1" in armbienEnv.txt and reboot 
(https://forum.armbian.com/topic/1524-orange-pi-one-how-to-enable-uart/)

thank you

**Comment by Laurent-Waltzapp** [comment]
Looks like it's disabled in the dts, so if you want to use it you have to add a patch in the kernel recipe to enable the uart1 node in arch/arm/boot/dts/sun8i-h3-orangepi-pc.dts
from
`&uart1 {
	pinctrl-names = "default";
	pinctrl-0 = <&uart1_pins>;
	status = "disabled";
};`
to
`&uart1 {
	pinctrl-names = "default";
	pinctrl-0 = <&uart1_pins>;
	status = "okay";
};`

**Comment by Halolo** [comment]
Looks like it's disabled in the dts, so if you want to use it you have to add a patch in the kernel recipe to enable the uart1 node in arch/arm/boot/dts/sun8i-h3-orangepi-pc.dts
from
`&uart1 { pinctrl-names = "default"; pinctrl-0 = <&uart1_pins>; status = "disabled"; };`
to
`&uart1 { pinctrl-names = "default"; pinctrl-0 = <&uart1_pins>; status = "okay"; };`

**Comment by serra82** [comment]
Thank you,
if can be useful to someone else, I followed this guide where is explained how make patch for openembedded:
https://www.toradex.com/blog/patching-kernel-in-openembedded
