### ISSUE TITLE
Orange Pi PC Plus

### ISSUE THREAD

**Issue by marckell** [Halolo/orange-pi-zero-distro#2]
Would you be interested in getting the Orange Pi PC Plus supported? I can supply hardware.

**Comment by Halolo** [comment]
The WiFi and onboard mmc are interesting additions. Maybe. For now I am still working on the Orange pi PC.

**Comment by nandra** [comment]
I have also PC plus and I need wifi working I'll work on it and share here. I'm using your layers to build image for PC plus and works fine. Can somebody please point me to latest PC plus schematics (I have some from 2016 but WIFI page is empty :( )

**Comment by nandra** [comment]
@marckell PR #4 is merged where support for orangepi-pc-plus was added (including wifi)
@Halolo maybe we can close this one?

**Comment by Halolo** [comment]
Yes, thank you for your work
